version: "3.9"

services:
  backend:
    build: ./backend
    container_name: netman_backend
    restart: unless-stopped
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: netman_frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - backend

  mongo:
    image: mongo
    container_name: netman_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
